name: PT Test Master Pipeline (Current → Major → Minor)

on:
  workflow_call:
  workflow_dispatch:

jobs:

  run-current:
    name: Run Test Current
    uses: ./.github/workflows/TestCurrent.yaml

  run-major:
    name: Run Test Next Major
    needs: run-current
    uses: ./.github/workflows/TestNextMajor.yaml

  run-minor:
    name: Run Test Next Minor
    needs: run-major
    uses: ./.github/workflows/TestNextMinor.yaml
